### ISSUE TITLE
Please enable auto-build for multitool-rdma definition.

### ISSUE THREAD

**Issue by disprosium8** [fabric-testbed/fabric-docker-images#78]
https://github.com/fabric-testbed/fabric-docker-images/tree/master/slice-vm-rocky9-multitool-rdma/0.0.1

**Comment by mjstealey** [comment]
Landing zone created here: https://hub.docker.com/repository/docker/fabrictestbed/slice-vm-rocky9-multitool-rdma/general

Build has succeeded

Closing
